HVMAPP/HVMAPP/Areas/HVM/Controllers/BilgisayarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HVMAPP.DAL;
using HVMAPP.Entity;

namespace HVMAPP.Areas.HVM.Controllers
{
    public class BilgisayarController : Controller
    {
        private HVMAPPDBCONTEXT db = new HVMAPPDBCONTEXT();

        // GET: HVM/Bilgisayar
        public ActionResult Listele()
        {
            var electronicStuffs = db.ElectronicStuffs.Include(e => e.LiveScreen).Include(e => e.Room);
            return View(electronicStuffs.ToList());
        }

        public ActionResult Detay(int? ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ElectronicStuff electronicStuff = db.ElectronicStuffs.Include(e => e.LiveScreen).Include(x=>x.Images).Include(e => e.Room).Where(x => x.ID == ID).FirstOrDefault();
            if (electronicStuff == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(electronicStuff);
        }

        // GET: HVM/Bilgisayar/Create
        public ActionResult Ekle()
        {
            
            ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true && x.LiveScreenName=="Tablet"), "ID", "LiveScreenName");
            ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name");
            ElectronicStuff electronicStuff = new ElectronicStuff();
            var LstES = db.ElectronicStuffs.OrderByDescending(c => c.ID).FirstOrDefault();
            return View(electronicStuff);
        }

        // POST: HVM/Bilgisayar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ekle(ElectronicStuff electronicStuff)
        {
            var data = db.ElectronicStuffs.Where(x => x.Name == electronicStuff.Name ||  x.RoomID==electronicStuff.RoomID).FirstOrDefault();
            var RS = db.RoomSettings.ToList();
            if (ModelState.IsValid)
            {

                if (data != null)
                {
                    ViewBag.Mesaj = "Yeni oluşturmak istediğiniz ekran sistemde mevcut bu yüzden yeni ekleme yapamıyoruz.";
                    ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
                    ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
                    return View(electronicStuff);
                }
                else
                {
                    if (RS.FirstOrDefault().Company==electronicStuff.CompanyName)
                    {
                        if (db.ElectronicStuffs.Count() < RS.FirstOrDefault().TabletNumber)
                        {
                            electronicStuff.UpdateDate = DateTime.Now;
                            db.ElectronicStuffs.Add(electronicStuff);
                            db.SaveChanges();
                            return RedirectToAction("Listele");
                        }
                        else
                        {
                            ViewBag.Mesaj = "Maksimum Oda Ekleme Sınırına Ulaştınız";
                            ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true && x.LiveScreenName == "Tablet"), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
                            ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
                            return View(electronicStuff);
                        }
                    }
                    else
                    {
                        ViewBag.Mesaj = "İşlem Sorunla Karşılaştı";
                        ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
                        ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
                        return View(electronicStuff);
                    }
                }
            }
            ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true && x.LiveScreenName == "Tablet"), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
            ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
            return View(electronicStuff);
        }

        // GET: HVM/Bilgisayar/Edit/5
        public ActionResult Guncelle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ElectronicStuff electronicStuff = db.ElectronicStuffs.Find(id);
            if (electronicStuff == null)
            {
                return HttpNotFound();
            }
            ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true && x.LiveScreenName == "Tablet"), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
            ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
            return View(electronicStuff);
        }

        // POST: HVM/Bilgisayar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guncelle(int Id,ElectronicStuff electronicStuff)
        {
            var ES = db.ElectronicStuffs.Include(x=>x.LiveScreen).Include(x=>x.Room).Where(x=>x.ID==Id).FirstOrDefault();
            var data = db.ElectronicStuffs.Where(x => x.Name == electronicStuff.Name  && x.RoomID == electronicStuff.RoomID && x.ID != Id).SingleOrDefault();
            var RS = db.RoomSettings.ToList();
            if (ModelState.IsValid)
            {
                if (data != null)
                {
                    ViewBag.Mesaj = "Güncellemek istediğiniz ekran bilgileri başka bir kayıtta mevcut olduğu için başka id ile üzerine yazma gerçekleştiremezsiniz.";
                    ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true && x.LiveScreenName == "Tablet"), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
                    ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
                    return View(data);
                }
                else
                {
                    if (RS.FirstOrDefault().Company == electronicStuff.CompanyName)
                    {
                        if (db.ElectronicStuffs.Count() < RS.FirstOrDefault().TabletNumber || db.ElectronicStuffs.Count() < RS.FirstOrDefault().TV || db.ElectronicStuffs.Count() < RS.FirstOrDefault().VideoWallNumber)
                        {
                            ES.ID = electronicStuff.ID;
                            ES.CompanyName = electronicStuff.CompanyName;
                            ES.IdentityNumber = electronicStuff.IdentityNumber;
                            ES.IsActive = electronicStuff.IsActive;
                            ES.LiveScreenID = electronicStuff.LiveScreenID;
                            ES.Name = electronicStuff.Name;
                            ES.RoomID = electronicStuff.RoomID;
                            ES.UpdateDate = DateTime.Now;
                            ES.ZipCode = electronicStuff.ZipCode;
                            ES.IpAddress = electronicStuff.IpAddress;
                            db.SaveChanges();
                            return RedirectToAction("Listele");
                        }
                        else
                        {
                            ViewBag.Mesaj = "İşlemde Hata Oluştu";
                            ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true && x.LiveScreenName == "Tablet"), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
                            ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
                            return View(electronicStuff);
                        }
                    }
                }

            }
            ViewBag.LiveScreenID = new SelectList(db.LiveScreens.Where(x => x.IsActive == true), "ID", "LiveScreenName", electronicStuff.LiveScreenID);
            ViewBag.RoomID = new SelectList(db.Rooms.Where(x => x.IsActive == true), "ID", "Name", electronicStuff.RoomID);
            return View(electronicStuff);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HVMAPP/HVMAPP/Areas/HVM/Views/Bilgisayar/Detay.cshtml
@model HVMAPP.Entity.ElectronicStuff

@{
    ViewBag.Title = "Ekran Ayarı Detayı";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">Ekran Detayı</h2>
    </header>
    <div class="panel-body">
        <div>
            <dl class="dl-horizontal">

                <dt>
                    Ekran Görünüm Adı
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LiveScreen.LiveScreenName)
                </dd>

                <dt>
                    Oda Adı
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Room.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    Tablet Zip Kodu
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ZipCode)
                </dd>

                <dt>
                    Tablet Giriş Şifresi
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IdentityNumber)
                </dd>

                <dt>
                    Şirket Adı
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CompanyName)
                </dd>
                <dt>Ekran Resimleri</dt>
                <dd>
                    <div class="col-md-12">
                        <section class="panel">
                            <header class="panel-heading">
                                <div class="panel-actions">
                                </div>

                                <h2 class="panel-title">Ekran Slider</h2>
                            </header>
                            <div class="panel-body">
                                <div class="owl-carousel" data-plugin-carousel data-plugin-options='{ "autoPlay": 2000, "items": 1,  "navigation": false, "pagination": false }'>
                                    @foreach (var item in Model.Images)
                                    {
                                        <div class="item">
                                            <img alt="Test" class="img-responsive" src="@item.ImageUrl">
                                        </div>
                                    }
                                </div>
                            </div>
                        </section>
                    </div>
                </dd>
                <dt></dt>
                <dd>
                    <a href="/HVM/Bilgisayar/Guncelle/@Model.ID" class="btn btn-primary"><i class="fa fa-edit"></i> Ekranı Güncelle</a>
                    <a href="@Url.Action("Listele","Bilgisayar")" class="btn btn-dark"><i class="fa fa-reply-all"></i> Listeye Geri Dön</a>
                </dd>
            </dl>
        </div>
    </div>
</section>

HVMAPP/HVMAPP/Areas/HVM/Views/Bilgisayar/Ekle.cshtml
@model HVMAPP.Entity.ElectronicStuff

@{
    ViewBag.Title = "Tablet Ekran Ekle";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">TABLET EKRANI EKLE</h2>
            </header>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @if (ViewBag.Mesaj != null)
                    {
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="alert alert-danger">
                                    <h3><i class="fa fa-warning"></i> Hata Mesajı</h3>
                                    <p>@ViewBag.Mesaj</p>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" class="form-control" required name="Name" placeholder="Lütfen Ekran İsmini Giriniz." />
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" class="form-control" name="ZipCode" placeholder="Zip Code Oda Numarası Olarak Ayarlayınız" required />
                            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" name="IdentityNumber" class="form-control" required placeholder="Lütfen Bir Kimlik Tanımlaması Yapın" maxlength="15" />
                            @Html.ValidationMessageFor(model => model.IdentityNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" name="IpAddress" class="form-control" required placeholder="Lütfen Bir İp Tanımlaması Yapın" maxlength="30" />
                            @Html.ValidationMessageFor(model => model.IpAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Ekran Seçiniz</label>
                        <div class="col-md-10">
                            @Html.DropDownList("LiveScreenID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LiveScreenID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Oda Seçiniz</label>
                        <div class="col-md-10">
                            @Html.DropDownList("RoomID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.RoomID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" class="form-control" name="CompanyName" value="Avrasya Hospital" required readonly />
                            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="checkbox">
                                <div class="i-checks">
                                    <label> <input type="radio" name="IsActive" value="True"> <i></i> Aktif </label>

                                    <label> <input type="radio" name="IsActive" value="False"> <i></i> Pasif </label>
                                    <label style="color:red;">Ekran Aktif veya Pasif Olarak Seçim Ayarlayınız.</label>
                                </div>
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Ekran Ekle</button>
                            <a href="@Url.Action("Listele","Bilgisayar")" class="btn btn-dark"><i class="fa fa-reply-all"></i> Listeye Geri Dön</a>
                        </div>
                    </div>
                </div>
                }
            </div>
        </section>

    </div>
</div>

HVMAPP/HVMAPP/Areas/HVM/Views/Bilgisayar/Guncelle.cshtml
@model HVMAPP.Entity.ElectronicStuff

@{
    ViewBag.Title = "Tablet Ekran Güncelle";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">TABLET EKRANI EKLE</h2>
            </header>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @if (ViewBag.Mesaj != null)
                    {
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="alert alert-danger">
                                    <h3><i class="fa fa-warning"></i> Hata Mesajı</h3>
                                    <p>@ViewBag.Mesaj</p>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" class="form-control" value="@Model.Name" required name="Name" placeholder="Lütfen Ekran İsmini Giriniz." />
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" value="@Model.ZipCode" class="form-control" readonly required placeholder="Zip Kod Giriniz" name="ZipCode" />
                            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" name="IdentityNumber" value="@Model.IdentityNumber" class="form-control" required placeholder="Lütfen Bir Kimlik Tanımlaması Yapın" maxlength="15" />
                            @Html.ValidationMessageFor(model => model.IdentityNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" name="IpAddress" value="@Model.IpAddress" class="form-control" required placeholder="Lütfen Bir İp Tanımlaması Yapın" maxlength="30" />
                            @Html.ValidationMessageFor(model => model.IpAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Ekran Seçiniz</label>
                        <div class="col-md-10">
                            @Html.DropDownList("LiveScreenID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LiveScreenID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Oda Seçiniz</label>
                        <div class="col-md-10">
                            @Html.DropDownList("RoomID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.RoomID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" class="form-control" name="CompanyName" value="@Model.CompanyName" required readonly />
                            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="checkbox">
                                <div class="i-checks">
                                    <label> <input type="radio" name="IsActive" value="True"> <i></i> Aktif </label>

                                    <label> <input type="radio" name="IsActive" value="False"> <i></i> Pasif </label>
                                    <label style="color:red;">Ekran Aktif veya Pasif Olarak Seçim Ayarlayınız.</label>
                                </div>
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Ekran Güncelle</button>
                            <a href="@Url.Action("Listele","Bilgisayar")" class="btn btn-dark"><i class="fa fa-reply-all"></i> Listeye Geri Dön</a>
                        </div>
                    </div>
                </div>
                }
            </div>
        </section>

    </div>
</div>

HVMAPP/HVMAPP/Areas/HVM/Views/Bilgisayar/Listele.cshtml
@model IEnumerable<HVMAPP.Entity.ElectronicStuff>
@{
    ViewBag.Title = "Bilgisayar Listele";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">EKRAN LİSTELE</h2>
    </header>
    <div class="panel-body">
        <table class="table table-bordered table-striped mb-none" id="datatable-tabletools" data-swf-path="assets/vendor/jquery-datatables/extras/TableTools/swf/copy_csv_xls_pdf.swf">
            <thead>
                <tr>
                    <th>Bilgisayar Adı</th>
                    <th>Bağlı Olan Odası</th>
                    <th>Bağlı Olan Ekranı</th>
                    <th>Güncelleme Tarihi</th>
                    <th>Aktif Durumu</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="gradeX">

                        <td>@item.Name</td>
                        <td>
                            @item.Room.Name
                        </td>
                        <td>@item.LiveScreen.LiveScreenName</td>
                        <td>@item.UpdateDate</td>
                        @if (item.IsActive == true)
                        {
                            <td><i class="fa fa-check"></i> Aktif</td>
                        }
                        else
                        {
                            <td><i class="fa fa-ban"></i> Pasif</td>
                        }
                    <td>
                        <a href="/HVM/Bilgisayar/Guncelle/@item.ID" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                        <a href="/HVM/Bilgisayar/Detay/@item.ID" class="btn btn-info"><i class="fa fa-eye"></i></a>
                    </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>