HVMAPP/HVMAPP/Areas/HVM/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HVMAPP.DAL;
using HVMAPP.Entity;

namespace HVMAPP.Areas.HVM.Controllers
{
    public class KullaniciController : Controller
    {
        private HVMAPPDBCONTEXT db = new HVMAPPDBCONTEXT();

        // GET: HVM/Kullanici
        public ActionResult Listele()
        {
            var userMembers = db.UserMembers.Include(u => u.RoleMember);
            return View(userMembers.ToList());
        }

        // GET: HVM/Kullanici/Create
        public ActionResult Ekle()
        {
            ViewBag.RoleMemberID = new SelectList(db.RoleMembers.Where(x=>x.IsActive==true), "ID", "RoleName");
            return View();
        }

        // POST: HVM/Kullanici/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ekle(UserMember userMember)
        {
            var data = db.UserMembers.Where(x => x.Username.ToUpper().ToLower() == userMember.Username.ToLower().ToUpper()).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (data!=null)
                {
                    ViewBag.Mesaj = "Böyle bir kullanıcı sistemde mevcut olduğu için yeni ekleme yapamıyoruz.";
                    ViewBag.RoleMemberID = new SelectList(db.RoleMembers.Where(x => x.IsActive == true), "ID", "RoleName", userMember.RoleMemberID);
                    return View(userMember);
                }
                else
                {
                    userMember.UpdateDate = DateTime.Now;
                    db.UserMembers.Add(userMember);
                    db.SaveChanges();
                    return RedirectToAction("Listele");
                }
            }

            ViewBag.RoleMemberID = new SelectList(db.RoleMembers.Where(x => x.IsActive == true), "ID", "RoleName", userMember.RoleMemberID);
            return View(userMember);
        }

        // GET: HVM/Kullanici/Edit/5
        public ActionResult Guncelle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserMember userMember = db.UserMembers.Find(id);
            if (userMember == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoleMemberID = new SelectList(db.RoleMembers.Where(x => x.IsActive == true), "ID", "RoleName", userMember.RoleMemberID);
            return View(userMember);
        }

        // POST: HVM/Kullanici/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guncelle(int Id, UserMember userMember)
        {
            var UM = db.UserMembers.Find(Id);
            var data = db.UserMembers.Where(x => x.Username.ToUpper().ToLower() == userMember.Username.ToLower().ToUpper() && x.ID != Id).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (data != null)
                {
                    ViewBag.Mesaj = "Böyle bir kullanıcı sistemde mevcut olduğu için aynı kullanıcı üstüne id'ler tutmadığı için güncelleme yapamıyoruz.";
                    ViewBag.RoleMemberID = new SelectList(db.RoleMembers.Where(x => x.IsActive == true), "ID", "RoleName", userMember.RoleMemberID);
                    return View(userMember);
                }
                else
                {
                    UM.ID = userMember.ID;
                    UM.CompanyName = userMember.CompanyName;
                    UM.IsActive = userMember.IsActive;
                    UM.Name = userMember.Name;
                    UM.Password = userMember.Password;
                    UM.RoleMemberID = userMember.RoleMemberID;
                    UM.Surname = userMember.Surname;
                    UM.UpdateDate = DateTime.Now;
                    UM.Username = userMember.Username;
                    db.SaveChanges();
                    return RedirectToAction("Listele");
                }

            }
            ViewBag.RoleMemberID = new SelectList(db.RoleMembers.Where(x => x.IsActive == true), "ID", "RoleName", userMember.RoleMemberID);
            return View(userMember);
        }

        // GET: HVM/Kullanici/Delete/5
        public ActionResult Sil(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserMember userMember = db.UserMembers.Include(x => x.RoleMember).Where(x => x.ID == id).FirstOrDefault();
            if (userMember == null)
            {
                return HttpNotFound();
            }
            return View(userMember);
        }

        // POST: HVM/Kullanici/Delete/5
        [HttpPost, ActionName("Sil")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserMember userMember = db.UserMembers.Include(x => x.RoleMember).Where(x => x.ID == id).FirstOrDefault();
            if (ModelState.IsValid)
            {
                db.UserMembers.Remove(userMember);
                db.SaveChanges();
                return RedirectToAction("Listele");
            }
            return View(userMember);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HVMAPP/HVMAPP/Areas/HVM/Views/Kullanici/Ekle.cshtml
@model HVMAPP.Entity.UserMember

@{
    ViewBag.Title = "Kullanıcı Ekle";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">KULLANICI EKLE</h2>
            </header>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @if (ViewBag.Mesaj != null)
                    {
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="alert alert-danger">
                                    <h3><i class="fa fa-warning"></i> Hata Mesajı</h3>
                                    <p>@ViewBag.Mesaj</p>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" maxlength="35" name="Name" class="form-control" required placeholder="Adınızı Giriniz(*)." />
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" maxlength="35" name="Surname" class="form-control" required placeholder="Soyadınızı Giriniz(*)." />
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" maxlength="25" name="Username" class="form-control" required placeholder="Kullanıcı Adı Giriniz(*). (Türkçe Karekter Kullanmayın)" />
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="password" class="form-control" required placeholder="Şifrenizi Giriniz(*)." maxlength="16" name="Password" />
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" class="form-control" value="Avrasya Hospital" readonly required placeholder="Şirket Giriniz(*)." maxlength="70" name="CompanyName" />
                            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.DropDownList("RoleMemberID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.RoleMemberID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="checkbox">
                                <div class="i-checks">
                                    <label> <input type="radio" name="IsActive" value="True"> <i></i> Aktif </label>

                                    <label> <input type="radio" name="IsActive" value="False"> <i></i> Pasif </label>
                                    <label style="color:red;">Kullanıcı Aktif veya Pasif Olarak Seçim Ayarlayınız.</label>
                                </div>
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-1 col-md-10">
                            <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Kullanıcı Ekle</button>
                            <a href="@Url.Action("Listele","Kullanici")" class="btn btn-dark"><i class="fa fa-reply-all"></i> Listeye Geri Dön</a>
                        </div>
                    </div>
                </div>
                }
            </div>
        </section>

    </div>
</div>

HVMAPP/HVMAPP/Areas/HVM/Views/Kullanici/Guncelle.cshtml
@model HVMAPP.Entity.UserMember

@{
    ViewBag.Title = "Kullanıcı Güncelle";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">KULLANICI GÜNCELLE</h2>
            </header>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @if (ViewBag.Mesaj != null)
                    {
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="alert alert-danger">
                                    <h3><i class="fa fa-warning"></i> Hata Mesajı</h3>
                                    <p>@ViewBag.Mesaj</p>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" maxlength="35" value="@Model.Name" name="Name" class="form-control" required placeholder="Adınızı Giriniz(*)." />
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" maxlength="35" value="@Model.Surname" name="Surname" class="form-control" required placeholder="Soyadınızı Giriniz(*)." />
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" maxlength="25" value="@Model.Username" name="Username" class="form-control" required placeholder="Kullanıcı Adı Giriniz(*). (Türkçe Karekter Kullanmayın)" />
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="password" class="form-control" value="@Model.Password" required placeholder="Şifrenizi Giriniz(*)." maxlength="16" name="Password" />
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.DropDownList("RoleMemberID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.RoleMemberID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" name="CompanyName" class="form-control" required readonly value="@Model.CompanyName" placeholder="Şirket Gir" />
                            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="checkbox">
                                <div class="i-checks">
                                    <label> <input type="radio" name="IsActive" value="True"> <i></i> Aktif </label>

                                    <label> <input type="radio" name="IsActive" value="False"> <i></i> Pasif </label>
                                    <label style="color:red;">Kullanıcı Aktif veya Pasif Olarak Seçim Ayarlayınız.</label>
                                </div>
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-1 col-md-10">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Kullanıcı Güncelle</button>
                            <a href="@Url.Action("Listele","Kullanici")" class="btn btn-dark"><i class="fa fa-reply-all"></i> Listeye Geri Dön</a>
                        </div>
                    </div>
                </div>
                }
            </div>
        </section>

    </div>
</div>

HVMAPP/HVMAPP/Areas/HVM/Views/Kullanici/Listele.cshtml
@model IEnumerable<HVMAPP.Entity.UserMember>
@{
    ViewBag.Title = "Kullanıcı Listele";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">KULLANICI LİSTELE</h2>
    </header>
    <div class="panel-body">
        <table class="table table-bordered table-striped mb-none" id="datatable-tabletools" data-swf-path="assets/vendor/jquery-datatables/extras/TableTools/swf/copy_csv_xls_pdf.swf">
            <thead>
                <tr>
                    <th>Rol Adı</th>
                    <th>Adı</th>
                    <th>Soyadı</th>
                    <th>Kullanıcı Adı</th>
                    <th>Aktif Durumu</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="gradeX">
                        <td>@item.RoleMember.RoleName</td>
                        <td>@item.Name</td>
                        <td>
                            @item.Surname
                        </td>
                        <td>@item.Username</td>
                        @if (item.IsActive == true)
                        {
                            <td><i class="fa fa-check"></i> Aktif</td>
                        }
                        else
                        {
                            <td><i class="fa fa-ban"></i> Pasif</td>
                        }
                        <td>
                            <a href="/HVM/Kullanici/Guncelle/@item.ID" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                            <a href="/HVM/Kullanici/Sil/@item.ID" class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

HVMAPP/HVMAPP/Areas/HVM/Views/Kullanici/Sil.cshtml
@model HVMAPP.Entity.UserMember
@{
    ViewBag.Title = "Kullanıcı Sil";
    Layout = "~/Areas/HVM/Views/Shared/_Layout.cshtml";
}
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">Kullanıcı Sil</h2>
    </header>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div>
                <dl class="dl-horizontal">
                    <dt>Rol Adı</dt>
                    <dd>@Model.RoleMember.RoleName</dd>
                    <hr />
                    <dt>Şirket Adı</dt>
                    <dd>@Html.DisplayFor(model=>model.CompanyName)</dd>
                    <hr />
                    <dt>
                        Adı
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <hr />
                    <dt>
                        Soyadı
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Surname)
                    </dd>
                    <hr />
                    <dt>
                        Kullanıcı Adı
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Username)
                    </dd>
                    <hr />
                    <dt>
                        Şifre
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Password)
                    </dd>
                    <hr />
                    <dt>
                        Son Güncelleme Tarihi
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UpdateDate)
                    </dd>
                    <hr />
                    <dt></dt>
                    <dd>

                        <div class="form-actions no-color">
                            <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Kullanıcı Sil</button>
                            <a href="@Url.Action("Listele", "Kullanici")" class="btn btn-dark"><i class="fa fa-reply-all"></i> Listeye Geri Dön</a>
                        </div>
                    </dd>
                    <hr />
                </dl>
            </div>
        }
    </div>
</section>